### ISSUE TITLE
Error executing s3remote

### ISSUE THREAD

**Issue by deepakjois** [bgahagan/git-remote-s3#1]
Details of my environment:

* OS X
* Checked out the repo using git. Did a `cargo build` and copied binary to PATH

```
> git push s3remote
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: std::sys_common::backtrace::print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic
   8: core::option::Option<T>::unwrap
   9: git_remote_s3::run
  10: git_remote_s3::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: std::rt::lang_start
  16: main
```

**Comment by bgahagan** [comment]
Hi @deepakjois , what url did you use to configure `s3remote`? Can you run `git remote get-url --all s3remote`? Is it in the format `s3://bucket/prefix`?

**Comment by deepakjois** [comment]
```
$ git remote get-url --all s3remote
s3://deepakjois-secrets
```

It does not have a prefix. I will try to add a prefix and test, but is it an error to _not_ specify prefix?

**Comment by deepakjois** [comment]
I can confirm that adding a prefix does fix the issue.

**Comment by bgahagan** [comment]
Thanks, I added some better error messages.  Yeah, currently a prefix is required; it allows multiple repos to be pushed to the same bucket with different prefixes.  But I could see it being useful to not have to specify a prefix if you're only ever planning to push one git repo to a bucket.  Created #2 to change the behaviour.
